//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.21 at 07:23:37 AM MDT 
//


package org.acme.specialtripsagency.flightservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.acme.specialtripsagency.flightservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AcmeFlightServiceFault_QNAME = new QName("urn:specialtripsagency.acme.org:flightservice", "AcmeFlightServiceFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.acme.specialtripsagency.flightservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BookingCancellationResponse }
     * 
     */
    public BookingCancellationResponse createBookingCancellationResponse() {
        return new BookingCancellationResponse();
    }

    /**
     * Create an instance of {@link AcmeFlightServiceFault }
     * 
     */
    public AcmeFlightServiceFault createAcmeFlightServiceFault() {
        return new AcmeFlightServiceFault();
    }

    /**
     * Create an instance of {@link FlightRequest }
     * 
     */
    public FlightRequest createFlightRequest() {
        return new FlightRequest();
    }

    /**
     * Create an instance of {@link Flight }
     * 
     */
    public Flight createFlight() {
        return new Flight();
    }

    /**
     * Create an instance of {@link BookingCancellation }
     * 
     */
    public BookingCancellation createBookingCancellation() {
        return new BookingCancellation();
    }

    /**
     * Create an instance of {@link Booking }
     * 
     */
    public Booking createBooking() {
        return new Booking();
    }

    /**
     * Create an instance of {@link BookingResponse }
     * 
     */
    public BookingResponse createBookingResponse() {
        return new BookingResponse();
    }
    
    /**
     * Create an instance of {@link FlightBookingFault }
     * 
     */
    public FlightBookingFault createFlightBookingFault() {
        return new FlightBookingFault();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcmeFlightServiceFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:specialtripsagency.acme.org:flightservice", name = "AcmeFlightServiceFault")
    public JAXBElement<AcmeFlightServiceFault> createAcmeFlightServiceFault(AcmeFlightServiceFault value) {
        return new JAXBElement<AcmeFlightServiceFault>(_AcmeFlightServiceFault_QNAME, AcmeFlightServiceFault.class, null, value);
    }

}
