package org.acme.specialtripsagency.hotelservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.17.redhat-1
 * 2016-02-05T22:11:52.891+01:00
 * Generated source version: 2.7.17.redhat-1
 * 
 */
@WebServiceClient(name = "AcmeHotelService", 
                  wsdlLocation = "file:/home/bernard/work/bpms-advanced/special-trips-agency-ws/hotel-service/src/main/webapp/wsdl/AcmeHotelService.wsdl",
                  targetNamespace = "urn:specialtripsagency.acme.org:hotelservice") 
public class AcmeHotelService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:specialtripsagency.acme.org:hotelservice", "AcmeHotelService");
    public final static QName AcmeHotelServiceInterfaceImplPort = new QName("urn:specialtripsagency.acme.org:hotelservice", "AcmeHotelServiceInterfaceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/bernard/work/bpms-advanced/special-trips-agency-ws/hotel-service/src/main/webapp/wsdl/AcmeHotelService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AcmeHotelService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/bernard/work/bpms-advanced/special-trips-agency-ws/hotel-service/src/main/webapp/wsdl/AcmeHotelService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AcmeHotelService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AcmeHotelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AcmeHotelService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AcmeHotelService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AcmeHotelService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AcmeHotelService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AcmeHotelServiceInterface
     */
    @WebEndpoint(name = "AcmeHotelServiceInterfaceImplPort")
    public AcmeHotelServiceInterface getAcmeHotelServiceInterfaceImplPort() {
        return super.getPort(AcmeHotelServiceInterfaceImplPort, AcmeHotelServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AcmeHotelServiceInterface
     */
    @WebEndpoint(name = "AcmeHotelServiceInterfaceImplPort")
    public AcmeHotelServiceInterface getAcmeHotelServiceInterfaceImplPort(WebServiceFeature... features) {
        return super.getPort(AcmeHotelServiceInterfaceImplPort, AcmeHotelServiceInterface.class, features);
    }

}
