package org.acme.specialtripsagency.flightservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.17.redhat-1
 * 2016-02-05T22:21:58.655+01:00
 * Generated source version: 2.7.17.redhat-1
 * 
 */
@WebServiceClient(name = "AcmeFlightService", 
                  wsdlLocation = "file:/home/bernard/work/bpms-advanced/special-trips-agency-ws/flight-service/src/main/webapp/wsdl/AcmeFlightService.wsdl",
                  targetNamespace = "urn:specialtripsagency.acme.org:flightservice") 
public class AcmeFlightService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:specialtripsagency.acme.org:flightservice", "AcmeFlightService");
    public final static QName AcmeFlightServiceInterfaceImplPort = new QName("urn:specialtripsagency.acme.org:flightservice", "AcmeFlightServiceInterfaceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/bernard/work/bpms-advanced/special-trips-agency-ws/flight-service/src/main/webapp/wsdl/AcmeFlightService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AcmeFlightService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/bernard/work/bpms-advanced/special-trips-agency-ws/flight-service/src/main/webapp/wsdl/AcmeFlightService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AcmeFlightService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AcmeFlightService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AcmeFlightService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AcmeFlightService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AcmeFlightService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AcmeFlightService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AcmeFlightServiceInterface
     */
    @WebEndpoint(name = "AcmeFlightServiceInterfaceImplPort")
    public AcmeFlightServiceInterface getAcmeFlightServiceInterfaceImplPort() {
        return super.getPort(AcmeFlightServiceInterfaceImplPort, AcmeFlightServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AcmeFlightServiceInterface
     */
    @WebEndpoint(name = "AcmeFlightServiceInterfaceImplPort")
    public AcmeFlightServiceInterface getAcmeFlightServiceInterfaceImplPort(WebServiceFeature... features) {
        return super.getPort(AcmeFlightServiceInterfaceImplPort, AcmeFlightServiceInterface.class, features);
    }

}
