package org.acme.specialtripsagency.flightservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.17.redhat-1
 * 2016-02-05T22:21:58.624+01:00
 * Generated source version: 2.7.17.redhat-1
 * 
 */
@WebService(targetNamespace = "urn:specialtripsagency.acme.org:flightservice", name = "AcmeFlightServiceInterface")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AcmeFlightServiceInterface {

    @WebMethod(action = "urn:specialtripsagency.acme.org:flightservice:cancelBooking")
    @WebResult(name = "BookingCancellationResponse", targetNamespace = "urn:specialtripsagency.acme.org:flightservice", partName = "parameters")
    public BookingCancellationResponse cancelBooking(
        @WebParam(partName = "parameters", name = "BookingCancellation", targetNamespace = "urn:specialtripsagency.acme.org:flightservice")
        BookingCancellation parameters
    );

    @WebMethod(action = "urn:specialtripsagency.acme.org:flightservice:bookFlight")
    @WebResult(name = "BookingResponse", targetNamespace = "urn:specialtripsagency.acme.org:flightservice", partName = "parameters")
    public BookingResponse bookFlight(
        @WebParam(partName = "parameters", name = "Booking", targetNamespace = "urn:specialtripsagency.acme.org:flightservice")
        Booking parameters
    );

    @WebMethod(action = "urn:specialtripsagency.acme.org:flightservice:listAvailablePlanes")
    @WebResult(name = "Flight", targetNamespace = "urn:specialtripsagency.acme.org:flightservice", partName = "parameters")
    public Flight listAvailablePlanes(
        @WebParam(partName = "parameters", name = "FlightRequest", targetNamespace = "urn:specialtripsagency.acme.org:flightservice")
        FlightRequest parameters
    );
}
